version: '3.4'

services:
  app:
    container_name: node
    build: .
    user: $UID:$GID
    ports:
      - '3000:3000'
    links:
      - mongo
    tty: true
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
  mongo:
    container_name: mongo
    image: mongo
    user: $UID:$GID
    ports:
      - '27017:27017'
    volumes:
      - ./data/mongo:/data/db
